version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
    labels:
      - chore
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          - major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
    labels:
      - chore
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          - major
